import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { useEffect, useState } from 'react'
import * as React from 'react'
import styles from '../styles/Home.module.css'
// https://www.swapi.tech/api/ 

type User = {
  name: string,
  email: string,
  address: {
    city: string,
    street: string,
  }
}
const Home: NextPage = () => {
  const [users, setUsers] = useState<User[]>([])
  const [isLoading, setIsLoading] = useState(false);
  useEffect(() => {
    setIsLoading(true);
    axios.get('https://jsonplaceholder.typicode.com/users/').then( response => {
      setUsers(response.data);
      setIsLoading(false);
    }, () => {
      setIsLoading(true)
    })
  }, []);

  return (
    <div>
      <Head>
        <title>Browser Side Render</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <h1>User List</h1>
       {isLoading?<div>Loading...</div>:
       <ul>
        {users.map((user, index) => (
          <li key={index}>Name: {user.name}<br/>Email: {user.email}<br/>Address: {user.address.city}</li>
        ))
}
        </ul>
       }
      </main>

      <footer className={styles.footer}>
        <br />
        <h1>Footer</h1>
      </footer>
    </div>
  )
}

export default Home
